source "https://rubygems.org"

# GitHub Pages gem (includes Jekyll and many plugins)
gem "github-pages", group: :jekyll_plugins

# Remote theme
gem "jekyll-remote-theme"

# Caching include fragments
gem "jekyll-include-cache"

# Native Windows file watcher (for `jekyll serve --livereload`)
gem "wdm", ">= 0.1", platforms: [:windows]

# Fiddle is required by some dependencies on Windows
gem "fiddle"
